# Permalinks
permalink:        pretty

collections:
  projects:
    output: true
  links:
    output: true
  music:
    output: true
  stories:
    output: true
  wikimusic:
    output: true            
    permalink: /wiki/:title