# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tom Critchlow Title
tagline:          My Github Site
url:              http://tomcritchlow.com
paginate:         1
baseurl:          /
author:
  name:           Tom Critchlow
  url:            https://twitter.com/tomcritchlow
  email:          tjcritchlow@gmail.com


collections:
  poetry:
    output: true
